export const Movies =[
     {id: 1, clip:'https://www.youtube.com/embed/0HyxQG4R-e8',name: 'Touhou Project: Walfas', rate:'Preview Rating: 8/10',genre: 'Genre: Comedy, Action, Drama', show:'Show Time: 29/05/2023', direct:'Director: Shanghai Alice',img:'assets/Posters/touhou.png',detail:'Mystic! Shrine Maiden Of Paradise! Hakurei Reimu! A Walfas Production Finally Got Green Lit By Zun (Team Shanghai Alice). Relive The Full "Touhou 14: Urban Legends In Limbo" In This One Big Goofy Adventure',},
    {id: 2, clip:'https://www.youtube.com/embed/itnqEauWQZM',name: 'Transformer X', rate:'Preview Rating: 6/10',genre: 'Genre: Action, Violent', show:'Show Time: 10/12/2023', direct:'Director: Sony',img:'assets/Posters/transformer.jpg',detail:'Yet Another Transformer Movie By the Main Man Michael Bays Himself. How Will This Bombastic Director Stun Us With Yet Another Robotic CGI Warare!',},
    {id: 3, clip:'https://www.youtube.com/embed/b3iQkqjLgPg',name: 'Bloom Into You', rate:'Preview Rating: 10/10',genre: 'Genre: Yuri, Drama, Romance, Anime',show: 'Show Time: 11/07/2023', direct:'Director: Seven Seas Entertainment',img:'assets/Posters/bloom.jpg',detail:'The story follows two female high school students, Yuu Koito and Touko Nanami, and the relationship that develops between them as they learn more about themselves through their experiences together.',},
    {id: 4, clip:'https://www.youtube.com/embed/Zi88i4CpHe4',name: 'Shazam: Fury Of The God', rate:'Preview Rating: 5.5/10',genre: 'Genre: Action, Teen Comedy',show:'Show Time: 29/08/2023', direct:'Director: Marvel Entertainment',img:'assets/Posters/shazam.jpg',detail:'Disrregarding The DC Comic Universe, Shazam Now Is A Group Of 7 Orphants Banding Together To Protect New York From Interdimesional Threats. Yet, They Themselves Are At Odd With Each Other When Billy Baston Refuses To Let Them Go On Their Seperate Path.',},
    {id: 5, clip:'https://www.youtube.com/embed/mYd_l3E7yOc',name: 'Witch From Mecury 2', rate:'Preview Rating: 8.5/10',genre: 'Genre: Yuri, Drama, Action, Anime',show:'Show Time: 31/6/2023', direct:'Director: Animax Asia',img:'assets/Posters/gundam.jpg',detail:'The Unexpected Turn To Make Gundam Into An Yuri Action Sci-fi Adventure! Join Suletta Mercury On Her First Year Surviving Her New Wife And The Bizzare shenanigans Revolving Her Mysterious Robot.',},
    {id: 6, clip:'https://www.youtube.com/embed/JqcncLPi9zw',name: 'Guardian Of the Galaxy 3', rate:'Preview Rating: 9.5/10',genre: 'Genre: Adult Comedy, Action', show:'Show Time: 12/11/2023', direct:'Director: Marvel - James Gun',img:'assets/Posters/guard3.jpg',detail:'James Gun Finally Did It. Finally, An MCU Movie In Phase 4 That Is No Trash. Withness The Aftermath Of Endgame, Love-and-Thunder, Christmas-special That Shaped These Beloved Comedic Guardian.',},
    {id: 7, clip:'https://www.youtube.com/embed/f-zqS2CiZqw',name: 'Five Nights At Freddy', rate:'Preview Rating: 8/10',genre: 'Genre: Horror, Vintage', show:'Show Time: 19/5/2023', direct:'Director: Scott Carton', img:'assets/Posters/fnaf.jpg',detail:'Scoot Carton After So Much Delay Has Finally Release A Canon Five Nights At Freddy Compiling A Coherent Story Of The First 4 Games. Relive The Classic Jumpscare Horror On The BIG SCREEN.',},
    {id: 8, clip:'https://www.youtube.com/embed/shW9i6k8cB0',name: 'Spider Man: Across The Spiderverse', rate:'Preview Rating: 10/10',genre: 'Genre: Teen Comedy, Action, Animation',show:'Show Time: 30/08/2023', direct:'Director: Sony - Marvel',img:'assets/Posters/spider.jpg',detail:'Spider Man, Spider Man, There Is Now A Black Spider Man. Aint Use Web - But A Gun. Born And Create On The Hood. WATCH OUT! Here Come The Black Spider Man.',},
    {id: 9, clip:'https://www.youtube.com/embed/uv6yK47m564',name: 'Distric 9: Local Ice Fairy', rate:'Preview Rating: 9/10',genre: 'Genre: Action, Scifi',show:'Show Time: 20/05/2023',direct:'Director: Shanghai Alice',img:'assets/Posters/cirno.jpg',detail:'BAKA BAKA BAKA Ice Fairy Of The Lake. The Fact The Cirno Manage To Not Get Herself Exterminated Is A Miracle. Yet At Time Of Crisis, the Power Of The "Strongest Local Ice Fairy" Will Be the Sole Factor That Defeat The Pure And Xenophobic Lunarian.',}
  ];